 raP       1   version 5    EditorData ì   addons  Opcan_Mod_Config  AddonsMetaData á  randomSeed ê‹ﬁ  ScenarioData Ô   Mission   1   moveGridStep   Ä?angleGridStep í
Ü>scaleGridStep   Ä?autoGroupingDist    Atoggles    ItemIDProvider    Camera ,  á   nextID E  ,   pos u≠eF“hB}[ÇFdir ∞õ˙æÇÜ	øR„/?up ¢õüæ«ÁW?$
‡>aside ‹ÜP? D6é?á    List ó  Ô   items     Item0 ¥  Ô    className Opcan_Mod_Config  name Opcan_Mod_Config Ô    author sukar42     Intel %   Entities x  1   timeOfChanges  ·DstartWeather öôô>startWind ÕÃÃ=startWaves ÕÃÃ=forecastWeather öôô>forecastWind ÕÃÃ=forecastWaves ÕÃÃ=forecastLightnings ÕÃÃ=rainForced    lightningsForced    wavesForced    windForced    year Û  month    day    hour    minute     startFogDecay B`e<forecastFogDecay B`e<x   items     Item0 L   Item1 û   Item2    Item3 ü   Item4 N   Item5 ˝   Item6 ¨   Item7 [   Item8 
	   Item9 π	   Item10 h
   Item11    Item12 ∆   Item13 u   Item14 $   Item15 ”   Item16 Ç  1    dataType Group  side East  Attributes ò  id ê   atlOffset R¯9Cû    û    dataType Group  side East  Attributes Í  id †   atlOffset R¯9C        dataType Object  PositionInfo a   side Empty flags     Attributes ô  id /   type OPCAN_MCDPM_A ü   position ◊ˇdF:x†AÅÇFangles     1@    ô    ü    dataType Object  PositionInfo    side Empty flags     Attributes H  id 0   type OPCAN_MCWPM_A N   position á
eF:x†AÍÖÇFangles     óõ@    H    N    dataType Object  PositionInfo ø   side Empty flags     Attributes ˜  id 1   type OPCAN_MCWPM_F ˝   position ”âeF%x†A£≈ÇFangles     Ë÷@    ˜    ˝    dataType Object  PositionInfo n   side Empty flags     Attributes ¶  id 2   type OPCAN_MCDPM_F ¨   position ÁÄeF%x†Ai¿ÇFangles     g⁄@    ¶    ¨    dataType Object  PositionInfo    side Empty flags     Attributes U  id 3   type OPCAN_MCDPM_R [   position ∞;eF:x†AgûÇFangles     z£@    U    [    dataType Object  PositionInfo Ã   side Empty flags     Attributes 	  id 4   type OPCAN_MCWPM_R 
	   position ìFeF:x†AI§ÇFangles     ò @    	    
	    dataType Object  PositionInfo {	   side Empty flags     Attributes ≥	  id 5   type OPCAN_CGAPM_A π	   position eF:x†AkäÇFangles     >N@    ≥	    π	    dataType Object  PositionInfo *
   side Empty flags     Attributes b
  id 6   type OPCAN_CGAPM_F h
   position HêeF%x†AùÃÇFangles     ‹@    b
    h
    dataType Object  PositionInfo Ÿ
   side Empty flags     Attributes   id 7   type OPCAN_CGAPM_R    position éQeF:x†AI™ÇFangles     πÿ@            dataType Object  PositionInfo à   side Empty flags     Attributes ¿  id 8   type OPCAN_ARDPM_A ∆   position ØeF:x†ANéÇFangles     '7@    ¿    ∆    dataType Object  PositionInfo 7   side Empty flags     Attributes o  id 9   type OPCAN_ARWPM_A u   position €(eF:x†AÂíÇFangles     ˆo@    o    u    dataType Object  PositionInfo Ê   side Empty flags     Attributes   id :   type OPCAN_ARDPM_F $   position jõeF%x†A^“ÇFangles     °B@        $    dataType Object  PositionInfo ï   side Empty flags     Attributes Õ  id ;   type OPCAN_ARWPM_F ”   position Œ¶eF%x†A!◊ÇFangles     {†@    Õ    ”    dataType Object  PositionInfo D   side Empty flags     Attributes |  id <   type OPCAN_ARWPM_R Ç   position ÆieF:x†AgµÇFangles     Tà@    |    Ç    dataType Object  PositionInfo Û   side Empty flags     Attributes +  id =   type OPCAN_ARDPM_R 1   position ˚]eF:x†AáØÇFangles     w¢@    +    1      